### PR TITLE
fixed issues with js changes

### PR DESCRIPTION
**Pull request by sharafcs50**
fixed issues wtih js - changes for card details, truncated text removed, added when lived to details.

### CODE REVIEW

**Comment by ghost** [comment]
I think you should to back this changes  
if (truncatedDescription.trim() === "N/A") {
    truncatedDescription = "This dinosaur has no description";
  }
because it influens on that 
image
Before changes it was 
image

**Comment by sharafcs50** [comment]
no, that is how it is in the Json file, some dinosaurs don't have a description by default.

**Comment by ghost** [comment]
I mean, It's more user-friendly to replace "N/A" from json to label "This dinosaur has no description";

**Review by ghost — APPROVED** [review]

**Comment by KseniiaRiabova** [comment]
Great comments @Nadiia-Lashtun , @sharafcs50 Good job, thanks for fixing issues

**Pull request merged**
